project_name: arc

before:
  hooks:
    - ./scripts/completions.sh

builds:
  - dir: arc
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 7
    ldflags:
      - -s -w -X github.com/hubci/arc/arc/cmd.version={{ .Version }} -extldflags "-static"
    env:
      - CGO_ENABLED=0

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}-v{{ .Version }}-{{ if eq .Os "darwin" }}macos{{ else }}{{ .Os }}{{ end }}-{{ .Arch }}{{ if .Arm }}hf{{ end }}
    files:
      - LICENSE
      - README.md
      - completions/*
    rlcp: true

nfpms:
  - package_name: hubci-arc
    file_name_template: "{{ .PackageName }}-v{{ .Version }}-{{ .Arch }}{{ if .Arm }}hf{{ end }}"
    homepage: "https://www.Feliciano.Tech"
    maintainer: "Ricardo N Feliciano <Ricardo@Feliciano.Tech>"
    description: "A helpful CircleCI and GitHub tool."
    license: MIT
    formats:
      - deb
    bindir: /usr/bin
    conflicts:
      - arc
    contents:
      - src: ./completions/arc.bash
        dst: /usr/share/bash-completion/completions/arc
        file_info:
          mode: 0644
      - src: ./completions/arc.fish
        dst: /usr/share/fish/vendor_completions.d/arc.fish
        file_info:
          mode: 0644
      - src: ./completions/arc.zsh
        dst: /usr/share/zsh/vendor-completions/_arc
        file_info:
          mode: 0644

brews:
  - tap:
      owner: hubci
      name: homebrew-tap
    commit_author:
      name: "Ricardo N Feliciano (FelicianoTech)"
      email: "Ricardo@Feliciano.Tech"
    folder: Formula
    homepage: "https://github.com/hubci/arc"
    description: "A helpful CircleCI and GitHub tool."
    test: |
      system "#{bin}/arc", "help"
    install: |-
      bin.install "arc"
      bash_completion.install "completions/arc.bash" => "arc"
      fish_completion.install "completions/arc.fish"
      zsh_completion.install "completions/arc.zsh" => "_arc"

checksum:
  name_template: "{{ .ProjectName }}-v{{ .Version }}-checksums.txt"
