project_name: arc

builds:
  - dir: arc
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - 7
    ldflags:
      - -s -w -X github.com/hubci/arc/arc/cmd.version={{ .Version }} -extldflags "-static"

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}{{ if .Arm }}hf{{ end }}"
    files:
      - LICENSE
      - README.md
    replacements:
      darwin: macos

nfpms:
  - package_name: hubci-arc
    file_name_template: "{{ .PackageName }}-v{{ .Version }}-{{ .Arch }}{{ if .Arm }}hf{{ end }}"
    homepage: "https://www.Feliciano.Tech"
    maintainer: "Ricardo N Feliciano <Ricardo@Feliciano.Tech>"
    description: "A helpful CircleCI and GitHub tool."
    license: MIT
    formats:
      - deb
    bindir: /usr/bin
    conflicts:
      - arc

brews:
  - tap:
      owner: hubci
      name: homebrew-tap
    commit_author:
      name: "Ricardo N Feliciano (FelicianoTech)"
      email: "Ricardo@Feliciano.Tech"
    folder: Formula
    homepage: "https://github.com/hubci/arc"
    description: "A helpful CircleCI and GitHub tool."
    test: |
      system "#{bin}/arc", "help"

checksum:
  name_template: "{{ .ProjectName }}-v{{ .Version }}-checksums.txt"
