version: 2.1

orbs:
  gor: hubci/goreleaser@1.0
  osd: circleci/os-detect@0.3.0

executors:
  linux-docker:
    docker:
      - image: cimg/base:2022.06
  linux-amd64:
    machine:
      image: ubuntu-2204:2022.04.2
  linux-arm64:
    machine:
      image: ubuntu-2004:2022.04.2
    resource_class: arm.medium
  macos:
    macos:
      xcode: 13.3.0
  windows:
    machine:
      image: windows-server-2019-vs2019:stable
      resource_class: windows.medium

workflows:
  main:
    jobs:
      - test
      - gor/release:
          version: "1.9.2"
          go-version: "1.18.3"
          dry-run: true
          post-steps:
            - persist_to_workspace:
                root: "."
                paths:
                  - "dist"
      - test-with-images:
          requires:
            - gor/release
          matrix:
            parameters:
              image:
                - linux-docker
                - linux-amd64
                - linux-arm64
                - macos
                #- windows
  release:
    jobs:
      - test:
          filters:
            branches:
              ignore: /.*/
            tags:
              # Simplified SemVer regex
              only: /^v\d+\.\d+\.\d+$/
      - gor/release:
          version: "1.9.2"
          go-version: "1.18.2"
          filters:
            branches:
              ignore: /.*/
            tags:
              # Simplified SemVer regex
              only: /^v\d+\.\d+\.\d+$/
          post-steps:
            - persist_to_workspace:
                root: "."
                paths:
                  - "dist"
          context: main-context
      - deb-publish:
          requires:
            - gor/release
          filters:
            branches:
              ignore: /.*/
            tags:
              # Simplified SemVer regex
              only: /^v\d+\.\d+\.\d+$/

jobs:
  test:
    docker:
      - image: cimg/go:1.18.3
    environment:
      GOTESTSUM_JUNITFILE: "junit/unit-tests.xml"
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run:
          name: "Download Dependancies"
          command: cd arc && go mod download
      - run:
          name: "Run Tests & Coverage"
          command: |
            cd ./arc
            mkdir junit
            gotestsum -- -coverprofile=coverage.txt -covermode=atomic ./...
            bash <(curl -s https://codecov.io/bash)
      - store_test_results:
          path: junit
      - store_artifacts:
          path: junit/unit-tests.xml
      - run:
          name: "Upload to Codecov"
          command: cd arc && bash <(curl -s https://codecov.io/bash)
      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/home/circleci/.cache/go-build"
  test-with-images:
    parameters:
      image:
        type: executor
    executor: <<parameters.image>>
    steps:
      - osd/init
      - attach_workspace:
          at: .
      - run: |
          V1=""

          if uname -m | grep "x86_64"; then
            V1="_v1"
          fi

          if [ $OSD_FAMILY == "linux" ]; then

            ./dist/arc_linux_$(dpkg --print-architecture)${V1}/arc version
          else
            ./dist/arc_darwin_amd64${V1}/arc version
          fi
  deb-publish:
    docker:
      - image: cimg/base:2022.06
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys
      - run: |
          echo 'pkg.atl.revidian.net ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBE16slz1okRPeUhxIpzBCn9rHqjk51ylxEYlYXvblswcxOQ0rPyAX6N8Bd2pnsh99xce/jaX2KJHPLPCc+zAXTg= root@li361-16' >> ~/.ssh/known_hosts
      - run: |
          ssh pkg@pkg.atl.revidian.net "mkdir ~/incoming/arc-${CIRCLE_TAG}"
          scp ./dist/*.deb pkg@pkg.atl.revidian.net:incoming/arc-${CIRCLE_TAG}/

          # Ubuntu 20.04 Focal
          ssh pkg@pkg.atl.revidian.net "aptly repo add ftech-ubuntu-focal ~/incoming/arc-${CIRCLE_TAG}/"
          ssh pkg@pkg.atl.revidian.net "aptly snapshot create ftech-ubuntu-focal--arc-${CIRCLE_TAG} from repo ftech-ubuntu-focal"
          ssh pkg@pkg.atl.revidian.net "aptly publish switch focal filesystem:ftech:/ubuntu ftech-ubuntu-focal--arc-${CIRCLE_TAG}"

          # Ubuntu 21.10 Impish
          ssh pkg@pkg.atl.revidian.net "aptly repo add ftech-ubuntu-impish ~/incoming/arc-${CIRCLE_TAG}/"
          ssh pkg@pkg.atl.revidian.net "aptly snapshot create ftech-ubuntu-impish--arc-${CIRCLE_TAG} from repo ftech-ubuntu-impish"
          ssh pkg@pkg.atl.revidian.net "aptly publish switch impish filesystem:ftech:/ubuntu ftech-ubuntu-impish--arc-${CIRCLE_TAG}"

          # Ubuntu 22.04 Jammy
          ssh pkg@pkg.atl.revidian.net "aptly repo add ftech-ubuntu-jammy ~/incoming/arc-${CIRCLE_TAG}/"
          ssh pkg@pkg.atl.revidian.net "aptly snapshot create ftech-ubuntu-jammy--arc-${CIRCLE_TAG} from repo ftech-ubuntu-jammy"
          ssh pkg@pkg.atl.revidian.net "aptly publish switch jammy filesystem:ftech:/ubuntu ftech-ubuntu-jammy--arc-${CIRCLE_TAG}"

          # Ubuntu Kinetic
          ssh pkg@pkg.atl.revidian.net "aptly repo add ftech-ubuntu-kinetic ~/incoming/arc-${CIRCLE_TAG}/"
          ssh pkg@pkg.atl.revidian.net "aptly snapshot create ftech-ubuntu-kinetic--arc-${CIRCLE_TAG} from repo ftech-ubuntu-kinetic"
          ssh pkg@pkg.atl.revidian.net "aptly publish switch kinetic filesystem:ftech:/ubuntu ftech-ubuntu-kinetic--arc-${CIRCLE_TAG}"

          ssh pkg@pkg.atl.revidian.net "rm -r ~/incoming/arc-${CIRCLE_TAG}"
